CREATE DATABASE SAVU;

USE SAVU;

DROP TABLE USUARIOS

CREATE TABLE USUARIOS
(IdUsuario INT IDENTITY PRIMARY KEY,
IdTipoUsuario INT NOT NULL,
NomeUsuario VARCHAR(200) NOT NULL,
CpfUsuario VARCHAR(11) NOT NULL,
DtNascimentoUsuario DATETIME NOT NULL,
EmailUsuario VARCHAR(200) NOT NULL,
Senha VARCHAR(30) NOT NULL,
Ativo BIT DEFAULT(0),
IdUsuarioCadastro INT NOT NULL,
DtCadastro DATETIME NOT NULL DEFAULT(GETDATE()),
IdUsuarioUltimaAtualizacao INT NULL,
DtUltimaAtualizacao DATETIME NULL);

CREATE TABLE TIPOUSUARIOS
(IdTipoUsuario INT IDENTITY PRIMARY KEY,
NomeTipoUsuario VARCHAR(200) NOT NULL,
DescricaoTipoUsuario VARCHAR(255) NOT NULL,
Ativo BIT DEFAULT(0),
IdUsuarioCadastro INT NOT NULL,
DtCadastro DATETIME NOT NULL DEFAULT(GETDATE()),
IdUsuarioUltimaAtualizacao INT NULL,
DtUltimaAtualizacao DATETIME NULL);

CREATE TABLE MARCAS_MONTADORAS
(IdMarcaMontadora INT IDENTITY PRIMARY KEY,
NomeMarcaMontadora VARCHAR(200) NOT NULL,
Ativo BIT DEFAULT(0),
IdUsuarioCadastro INT NOT NULL,
DtCadastro DATETIME NOT NULL DEFAULT(GETDATE()),
IdUsuarioUltimaAtualizacao INT NULL,
DtUltimaAtualizacao DATETIME NULL);

CREATE TABLE MODELOS
(IdModelo INT IDENTITY PRIMARY KEY,
IdMarcaMontadora INT NOT NULL,
NomeModelo VARCHAR(200) NOT NULL,
IdCarroceria INT NOT NULL,
Ativo BIT DEFAULT(0),
IdUsuarioCadastro INT NOT NULL,
DtCadastro DATETIME NOT NULL DEFAULT(GETDATE()),
IdUsuarioUltimaAtualizacao INT NULL,
DtUltimaAtualizacao DATETIME NULL);

CREATE TABLE CARROCERIAS
(IdCarroceria INT IDENTITY PRIMARY KEY,
NomeCarroceria VARCHAR(200) NOT NULL,
Ativo BIT DEFAULT(0),
IdUsuarioCadastro INT NOT NULL,
DtCadastro DATETIME NOT NULL DEFAULT(GETDATE()),
IdUsuarioUltimaAtualizacao INT NULL,
DtUltimaAtualizacao DATETIME NULL);

CREATE TABLE TIPOCAMBIOS
(IdTipoCambio INT IDENTITY PRIMARY KEY,
NomeTipoCambio VARCHAR(200) NOT NULL,
Ativo BIT DEFAULT(0),
IdUsuarioCadastro INT NOT NULL,
DtCadastro DATETIME NOT NULL DEFAULT(GETDATE()),
IdUsuarioUltimaAtualizacao INT NULL,
DtUltimaAtualizacao DATETIME NULL);

CREATE TABLE VEICULOS
(IdVeiculo INT IDENTITY PRIMARY KEY,
IdMarcaMontadora INT NOT NULL,
IdModelo INT NOT NULL,
IdCarroceria INT NOT NULL,
IdTipoCambio INT NOT NULL,
AnoInicioVeiculo INT NOT NULL,
AnoFimVeiculo INT NOT NULL,
IdUsuarioCadastro INT NOT NULL,
DtCadastro DATETIME NOT NULL DEFAULT(GETDATE()),
IdUsuarioUltimaAtualizacao INT NULL,
DtUltimaAtualizacao DATETIME NULL);

